using System.Collections;
using NUnit.Framework;
using Unity.RecordedTesting;
using Unity.CloudTesting;
using UnityEngine.TestTools;

namespace GeneratedAutomationTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording: "Recordings/Test Start Gane.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public class Tests_Test_Start_Gane : RecordedTestSuite
    {
        /// <summary>
        /// Asserts that the recording can successfully play through to the end. 
        /// </summary>
        [UnityTest]
        [CloudTest]
        [RecordedTest("Recordings/Test Start Gane.json")]
        public IEnumerator CanPlayToEnd()
        {
            yield return RecordedTesting.TestPlayToEnd();
            Assert.IsTrue(true);
        }
    }
}
